server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

---

spring:
  profiles: docker
  application:
    name: chatty-service-discovery

eureka:
  instance:
    hostname: chatty-service-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://chatty-service-discovery:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0