server:
  port: ${PORT:8080}
spring:
    data:
     mongodb:
        uri: mongodb://localhost:27017/chatty-database
    hateoas:
      use-hal-as-default-json-media-type: false
---

spring:
  profiles: docker
  data:
     mongodb:
        uri: mongodb://mongodb:27017/chatty-database
  hateoas:
    use-hal-as-default-json-media-type: false
server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://chatty-service-discovery:8761/eureka/
